# 固定値は、業務上明示されたものだけに限定する。
MAGITOKU_AFTER_FACTOR = 0.90

BUDGET_STEP = 1000
UP_RATE = 1.15
DOWN_RATE = 0.85

# 係数算出時の参照期間
RECENT_NORMAL_DAYS = 28
TRANSITION_NORMAL_DAYS = 28

# 大規模媒体判定
PREMIUM_MEDIA_KEYWORDS = ("ハピタス", "モッピー", "LINE")

# 定常予測の学習設定
RECENCY_MONTH_DECAY = 0.80  # 1か月古い実績は直近月の80%の重み
OUTLIER_MIN_DAYS = 14      # これ未満の日数では異常値を自動除外しない
OUTLIER_MAD_Z_THRESHOLD = 3.5  # log1p(CV)のMADベースrobust z-score閾値
FACTOR_PRIOR_DAYS = 14       # 係数の少数実績を1.0側へ縮める事前日数

# 休眠媒体判定
INACTIVE_MEDIA_LOOKBACK_DAYS = 30  # 予測時点直近30日でCV=0の媒体は定常予測対象から除外

# 単価感応度（媒体別）の安全設定
UNIT_PRICE_MIN_MONTHS = 3
UNIT_PRICE_PRIOR_MONTHS = 4
UNIT_PRICE_ELASTICITY_MIN = -0.5
UNIT_PRICE_ELASTICITY_MAX = 1.5
UNIT_PRICE_FACTOR_MIN = 0.70
UNIT_PRICE_FACTOR_MAX = 1.30

# 案件全体トレンド補正（掲載継続とは分離し、同じ継続媒体群のCV水準変化を見る）
GLOBAL_TREND_WINDOW_DAYS = 30
GLOBAL_TREND_MIN_DAYS = 5
GLOBAL_TREND_MIN_STABLE_MEDIA = 3
GLOBAL_TREND_PRIOR_DAYS = 7
GLOBAL_TREND_FACTOR_MIN = 0.70
GLOBAL_TREND_FACTOR_MAX = 1.30
